[APP-733] Restrict validation rules for Hashes
peopleforce/validate_params pull request #66
Opened 2024-04-15 17:08 UTC by psyxoz

Related to https://peopleforce.atlassian.net/browse/APP-733

2024-04-15 21:31 UTC, acetinick requested changes

2024-04-15 21:31 UTC, acetinick commented on spec/validate_params/validatable/nested_spec.rb
> +xdescribe ValidateParams::Validatable do
Fix

2024-04-16 05:22 UTC, psyxoz commented on spec/validate_params/validatable/nested_spec.rb
> +xdescribe ValidateParams::Validatable do
```suggestion
describe ValidateParams::Validatable do
```

2024-04-16 05:22 UTC, psyxoz commented on spec/validate_params/validatable/nested_spec.rb
> +xdescribe ValidateParams::Validatable do
Done ✅

2024-04-16 10:41 UTC, psyxoz commented on spec/validate_params/validatable/nested_spec.rb
> +describe ValidateParams::Validatable do
```suggestion
xdescribe ValidateParams::Validatable do
```

2024-04-16 10:46 UTC, merged